# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FFRPC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x46\x46RPC.proto\x12\x05\x66itow\"\x14\n\x05m_ids\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x17\n\x08m_length\x12\x0b\n\x03len\x18\x01 \x01(\x04\"`\n\nm_instance\x12\x13\n\x0bignore_flag\x18\x01 \x01(\r\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x02\x12\x12\n\nbbox_label\x18\x03 \x01(\t\x12\x1b\n\x04mask\x18\x04 \x03(\x0b\x32\r.fitow.m_mask\"@\n\x06m_bbox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"\x18\n\x06m_mask\x12\x0e\n\x06points\x18\x01 \x03(\x02\"\x8b\x01\n\x0cm_image_info\x12\x10\n\x08img_path\x18\x01 \x01(\t\x12\x0e\n\x06img_id\x18\x02 \x01(\x05\x12\x14\n\x0cseg_map_path\x18\x03 \x01(\t\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12$\n\tinstances\x18\x06 \x03(\x0b\x32\x11.fitow.m_instance\"`\n\x0em_label_stream\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0b\n\x03len\x18\x02 \x01(\x04\x12\x0b\n\x03ids\x18\x03 \x03(\t\x12\'\n\nimage_info\x18\x04 \x01(\x0b\x32\x13.fitow.m_image_info\"\x14\n\x05m_say\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xf5\x01\n\x05\x46\x46RPC\x12&\n\x06GetIDs\x12\x0c.fitow.m_say\x1a\x0c.fitow.m_ids\"\x00\x12,\n\tGetLength\x12\x0c.fitow.m_say\x1a\x0f.fitow.m_length\"\x00\x12/\n\x0fGetDatasetInfos\x12\x0c.fitow.m_say\x1a\x0c.fitow.m_say\"\x00\x12-\n\tHeartBeat\x12\x0c.fitow.m_say\x1a\x0c.fitow.m_say\"\x00(\x01\x30\x01\x12\x36\n\tGetLabels\x12\x0c.fitow.m_say\x1a\x15.fitow.m_label_stream\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FFRPC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _M_IDS._serialized_start=22
  _M_IDS._serialized_end=42
  _M_LENGTH._serialized_start=44
  _M_LENGTH._serialized_end=67
  _M_INSTANCE._serialized_start=69
  _M_INSTANCE._serialized_end=165
  _M_BBOX._serialized_start=167
  _M_BBOX._serialized_end=231
  _M_MASK._serialized_start=233
  _M_MASK._serialized_end=257
  _M_IMAGE_INFO._serialized_start=260
  _M_IMAGE_INFO._serialized_end=399
  _M_LABEL_STREAM._serialized_start=401
  _M_LABEL_STREAM._serialized_end=497
  _M_SAY._serialized_start=499
  _M_SAY._serialized_end=519
  _FFRPC._serialized_start=522
  _FFRPC._serialized_end=767
# @@protoc_insertion_point(module_scope)
